### ISSUE TITLE
Only works on visible files

### ISSUE THREAD

**Issue by jrobichaud** [lixinliang/tree-view-search-bar#1]
If a folder is collapsed a file will not appear in search results.

**Comment by lixinliang** [comment]
That is definitely right.
Perhaps I will fixed that later....

**Comment by cliffordfajardo** [comment]
I'm also having problems viewing files & opening folders after searching. 

This is happening in Atom beta latest & regular Atom
![search-bar](https://cloud.githubusercontent.com/assets/6743796/18368133/39a524a8-75d3-11e6-8903-1d18a53d6ee3.gif)

**Comment by lixinliang** [comment]
Searching with `node_modules` that will only display the folder.

If you hope to display the folder and its subfiles, please input `node_modules\`.

document is here
https://github.com/lixinliang/tree-view-search-bar#Path

I will add an English version later.

**Comment by lixinliang** [comment]
It's still a problem.

Now, I filter the files in tree view, base on the files are exist in DOM tree(html tag).
I am considering that it is deserved to resolved.

Some times, we know the files which we hope to search are in collapsed directory.
Usually, we expanded them manually, it's ok.

If it would works on collapsed directory, that mean I have to use nodejs to filter the files at the same time.
And how to tell users clearly, 'hey, there're some files maybe you need in here.'.
For example, make a `!` after the directory name. That's a problem....

If you guys have good idea, welcome to move here #3  to discuss.

Now, I closed this.
