### ISSUE TITLE
Did not work in my editor

### ISSUE THREAD

**Issue by bahattinz** [lixinliang/tree-view-search-bar#12]
Hi, 

Congratulations on this beautiful work. I am using Atom 1.16.0 x64 on Kubuntu 16.04 64 bit. I installed it successfully but it did not work. He works for my friend but I do not.

Good works..

**Comment by lixinliang** [comment]
In Atom 1.16.0, it has a problem exactly.
I think that it's the same problem as #10.
Probably, I would publish a patch to fix it recently.

**Comment by lixinliang** [comment]
[0.1.4](https://github.com/lixinliang/tree-view-search-bar/releases/tag/v0.1.4) is published.
