### ISSUE TITLE
Thinking this plugin would be better considered 'tree-view-filter'

### ISSUE THREAD

**Issue by mikeerickson** [lixinliang/tree-view-search-bar#5]
As it really performs a filter, not a search?

**Comment by lixinliang** [comment]
Thanks for your recommendation.
`tree-view-filter` is nice, and seems to be smarter.

Absolutely, `tree-view-search-bar` is like a filter more than a search...

I did not find any similar plugin before. 
(I searched the key word `filter` before, but the results were not quite what I want.)
So I created one by myself.

Now I will consider it.

**Comment by lixinliang** [comment]
@mikeerickson
I suddenly think of it, I used `tree-view-filter` before and it really was not what I want.
- `tree-view-filter` could not filter the directory. 
- And it must input the extname, I'd like to filter the files without extname more than input a redundant `.*`.

**Comment by mikeerickson** [comment]
Ah yes, I see what you mean now.  Unfortunately they took the name and partially fail at solution, whereas your plugin works but has deceptive name.

**Comment by lixinliang** [comment]
Well, that's it.
I add the keyword "filter", hope that more people could find it.

**Comment by mikeerickson** [comment]
Works for me, now just need to add a good (easy) keymap.  Not that I can't easily do that myself, just thinking out loud.
